#ifndef MANAGETOOLWND_H_INCLUDED
#define MANAGETOOLWND_H_INCLUDED

//Размеры
#define WIDTH_MANAGETOOL_WND 350
#define HEIGHT_MANAGETOOL_WND 350
//Пользовательские сообщения
#define WM_REDRAW_AUX_WINDOW WM_USER
#define WM_CHECK_MENU_ITEM WM_USER + 1
#define WM_PRESOLVE WM_USER + 2
#define WM_CLEAR_SOLUTION WM_USER + 3

LRESULT CALLBACK ManageToolWndProc(HWND, UINT, WPARAM, LPARAM);

#endif // MANAGETOOLWND_H_INCLUDED
